[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools", "setuptools-scm"]

[project]
classifiers = ["Programming Language :: Python :: 3"]
dependencies = []
description = "python-template"
name = "python-template"
readme = "README.md"
requires-python = ">=3.10"
version = "0.0.1"

[project.optional-dependencies]
dev = [
  "isort == 5.11.4",
  "black == 22.12.0",
  "mypy == 0.991",
  "nox == 2022.11.21",
  "pytest == 7.2.1",
  "flake8 == 6.0.0",
  "flake8-bugbear == 23.1.20",
  "flake8-comprehensions == 3.10.1",
  "pep8-naming == 0.13.3",
  "pyproject-flake8 == 6.0.0.post1",
  "pytest-cov == 4.0.0",
]

[tool.mypy]
disable_error_code = "misc"
exclude = "migrations"
strict = true

[tool.flake8]
exclude = "venv,.nox,docs"
extend-ignore = ["E203"]
extend-immutable-calls = ["Argument"]
max-doc-length = 72
max-line-length = 99

[tool.black]
line-length = 99
target-version = ["py310"]

[tool.isort]
force_sort_within_sections = true
line_length = 99
profile = "black"
skip_gitignore = true
src_paths = ["src"]
